#' @title Download RedCap Report
#'
#' @description This function queries the RedCap API to download a specified report using the provided API token
#' and URL. The report is identified by its unique report ID. The function returns the contents of
#' the report as a tibble.
#'
#' @param redcapTokenName A character string specifying the name of the API token stored in the
#'                         user's .REnviron file.
#' @param redcapUrl A character string specifying the URL of the RedCap server.
#' @param redcapReportId A character string specifying the unique ID of the RedCap report to be downloaded.
#'
#' @return A tibble containing the contents of the downloaded RedCap report.
#'
#' @importFrom httr POST http_error
#' @importFrom readr read_csv
#'
#' @export
#'
#' @examples
#' # Download RedCap report using token from .REnviron file
#' redcapToken = "REDCAP_API_TOKEN"
#' redcapUrl = "https://redcap.example.com/api/"
#' redcapReportId = "123456"
#' report_data = downloadRedcapReport(redcapToken, redcapUrl, redcapReportId)
#' head(report_data)
#'

downloadRedcapReport = function(redcapTokenName,redcapUrl,redcapReportId){
  # Fetch redcap API token from .Renviron file
  api_token = Sys.getenv(redcapTokenName)

  # Define formData using autogenerated Redcap R script details
  formData = list(
    "token" = api_token,
    content = 'report',
    format = 'csv',
    report_id = redcapReportId,
    csvDelimiter = '',
    rawOrLabel = 'raw',
    rawOrLabelHeaders = 'raw',
    exportCheckboxLabel = 'false',
    returnFormat = 'csv'
  )

  # Send request to REDCap API
  redcapResponse = httr::POST(redcapUrl, body = formData, encode = "form")

  # Check for successful response
  if (httr::http_error(redcapResponse))
    stop("Failed to download Redcap Report.")

  # Extract content from response and convert to tibble
  result = httr::content(redcapResponse, as = "text")
  result.tibble = readr::read_csv(result)

  return(result.tibble)

}
